version: "3"

services:
  backend:
    build: ./backend/
    container_name: backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    command: "npm run dev"
    depends_on:
      - database

  database:
    image: mysql:latest
    volumes:
      - "./database/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./database/.db_tmp:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_matcha
      MYSQL_USER: user_matcha
      MYSQL_PASSWORD: "pass_matcha"